# Generated by Django 5.1.6 on 2025-02-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="Enter the content or URL")),
                (
                    "category",
                    models.CharField(
                        choices=[("text", "Text"), ("image_url", "Image URL")],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("is_reviewed", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Data Entries",
                "ordering": ["-timestamp"],
            },
        ),
    ]
