# Generated by Django 5.1.6 on 2025-02-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[("text", "Text"), ("image_url", "Image URL")],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_reviewed", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "entries",
                "ordering": ["-timestamp"],
            },
        ),
    ]
